INSERT INTO Players (id, name) VALUES (1, 'Djokovich');
INSERT INTO Players (id, name) VALUES (2, 'Nadal');
INSERT INTO Players (id, name) VALUES (3, 'Federer');
INSERT INTO Players (id, name) VALUES (4, 'Murray');
INSERT INTO Players (id, name) VALUES (5, 'Thiem');
INSERT INTO Players (id, name) VALUES (6, 'Zverev');
INSERT INTO Players (id, name) VALUES (7, 'Tsitsipas');
INSERT INTO Players (id, name) VALUES (8, 'Medvedev');
INSERT INTO Players (id, name) VALUES (9, 'Rublev');
INSERT INTO Players (id, name) VALUES (10, 'Berrettini');
ALTER SEQUENCE players_seq RESTART WITH 11;

INSERT INTO Matches (id, player1, player2, winner) VALUES (1, 1, 10, 10);
INSERT INTO Matches (id, player1, player2, winner) VALUES (2, 2, 9, 2);
INSERT INTO Matches (id, player1, player2, winner) VALUES (3, 3, 8, 8);
INSERT INTO Matches (id, player1, player2, winner) VALUES (4, 4, 7, 4);
INSERT INTO Matches (id, player1, player2, winner) VALUES (5, 5, 6, 5);
INSERT INTO Matches (id, player1, player2, winner) VALUES (6, 1, 9, 9);
INSERT INTO Matches (id, player1, player2, winner) VALUES (7, 2, 8, 8);
INSERT INTO Matches (id, player1, player2, winner) VALUES (8, 3, 7, 3);
INSERT INTO Matches (id, player1, player2, winner) VALUES (9, 4, 6, 6);
INSERT INTO Matches (id, player1, player2, winner) VALUES (10, 5, 10, 10);
INSERT INTO Matches (id, player1, player2, winner) VALUES (11, 6, 10, 6);
INSERT INTO Matches (id, player1, player2, winner) VALUES (12, 7, 9, 7);
INSERT INTO Matches (id, player1, player2, winner) VALUES (13, 1, 8, 1);
INSERT INTO Matches (id, player1, player2, winner) VALUES (14, 2, 7, 7);
INSERT INTO Matches (id, player1, player2, winner) VALUES (15, 3, 6, 3);
INSERT INTO Matches (id, player1, player2, winner) VALUES (16, 4, 5, 5);
INSERT INTO Matches (id, player1, player2, winner) VALUES (17, 9, 10, 10);
ALTER SEQUENCE matches_seq RESTART WITH 18;